language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Uv5nD4Of6rztjTf7s5uXb8E5xs9N/+YjJeJMaMzLY/qDhXTe/9PlOM4FZBXTbOPA6n1VFPEoLojxa9wcStKVh/vKBMl44mTD1TdQm+p10sfdqX65dP5WS2J2Ne3kjdsIHzmooct8NURjuRvr+s7uqrpcfaZ1V7di1om7IuGFht6mOwZKN+F1n4TCK+CBePY6Mgo7u/eZMGHNl9Zf89CZiTdbfrPVowA/ZD82YTSGtqsFAI67qltrgFfsmrR1+nAUvSPDJZOzEFusj5J9Lgxpl6Zqsnte666Tx3yzWR+J8AO18lWkgvYp+oSW5WEhxBPuXSjGqN9rFV/sXpBgwkPVQFV4B+D4wFMb/xbVwYUIJQ/qpzRIF45jfPrwBDg0WIXG6o9z2jixnPV3/j6V5HYdb4zvlS4iwa/2PFHBK3lW4NdUcMZUxyaof8xXG62Xkrfo4JPVilVZMcgXe+csWLREWD6nXZchmxqfu8clB0XOKa09lKGcQ1U/UZeruhEHV8Ni+k7TsxodJMJ43ColGtVQRfIgdgMFDMLngi6/X8lyYXtOdpd3+H5pc6WTpfPKYQumlhBbE6BDI0qr9VgPoCVQJqFtObCbBQFL+NhQFflj6hl7r5VCzRA41iNX9mMw8veocbknp1irsDW8Gsoc0LvkDSrXYfJRXTnb3lbBx07RlSM=
  app: get-swole-api
  on:
    repo: tranpeter08/GetSwole-API
